spring:
  datasource:
    # URL kết nối đã được sửa để trỏ tới instance MSSQLSERVER01 của máy DAOHUY
    url: jdbc:sqlserver://localhost;instanceName=MSSQLSERVER01;databaseName=FashionStoreDB;encrypt=true;trustServerCertificate=true;
    # Điền tài khoản đăng nhập SQL Server (thường là sa)
    username: sa
    # Điền mật khẩu SQL Server của bạn
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
