spring:
  datasource:
    # Cấu hình kết nối SQL Server chuẩn (đã bật hỗ trợ Tiếng Việt Unicode)
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=FashionStoreDB;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;characterEncoding=UTF-8;stringtype=nvarchar;}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:sa}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server.error.include-stacktrace: never
server.error.include-message: never

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

payos:
  client-id: ${PAYOS_CLIENT_ID:e14c939a-e8da-4b9f-81bd-25f05b31417c}
  api-key: ${PAYOS_API_KEY:6ab5f354-952c-4bbf-856c-042ae5731b1a}
  checksum-key: ${PAYOS_CHECKSUM_KEY:4467e43ad05fc1268f90844cfe29d92a7e37e32dfdb08dc59d3dac123ee23a51}
